### ISSUE TITLE
FSharp.Core doc comments are gone in tooltips in VS 16.7.1 and 16.7.2

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#10041]
Since at least 16.7.1, there are no doc comments anymore for FSharp.Core library functions. Sometimes there's a tooltip with the signature, but no doc comment, sometimes there's no tooltip.

Expected:

![image](https://user-images.githubusercontent.com/16015770/91703753-fbb98b80-eb7a-11ea-99eb-830442ebd3bb.png)

Actual:

![image](https://user-images.githubusercontent.com/16015770/91703804-0d9b2e80-eb7b-11ea-8b6b-91fcacdaee36.png)

And in `VisualFSharp.sln`, there are no tooltips at all for functions from FSharp.Core, however, self-build and BCL functions give proper tooltips.

The doc comments appear correctly in the context-sensitive dropdown when you type the `.`. So it's not that they're gone or something, they're just not shown in normal tooltips.

The tooltips work correctly in VS Preview editions, but if possible, I would like that fix merged with the 16.7 branch for 16.7.3, as it is currently broken and may be some time before 16.8 becomes final.

**Comment by dsyme** [comment]
@cartermp This is an important thing to fix.  We do keep regressing this (it is currently regressed in scripts too!) and we should work out how to unit test it better.

**Comment by abelbraaksma** [comment]
> and we should work out how to unit test it better.

I've seen in some companies where I worked unit tests that fired up an application and ran a macro-script moving the mouse etc in a VM and took a screenshot of the window. Some of these screenshots where just stored and needed to be manually verified before shipping, others where pixel for pixel compared with a certain error margin.

Not sure that's possible here, though perhaps just taking some screenshots on each CI run would already help finding these issues before any (major) merge.

**Comment by cartermp** [comment]
I would verify that it's the same binary being used, since I see you're trialing string interpolations. This would mean either something is regressed or something is fixed if you're seeing a discrepancy.

**Comment by abelbraaksma** [comment]
@cartermp, it's the other way around. This was observed in 16.7.2 rtm. The screenshot showing the interpolations is VS preview, where it does work correctly. It fails in all current rtm releases.

I can try in a vm if it doesn't repro for you.

**Comment by cartermp** [comment]
Right, in this case it would be that something is fixed in the preview builds.

**Comment by abelbraaksma** [comment]
@cartermp, I've done some more testing:

* Launched new VM with fresh 16.7.2: tooltips work as expected
* On my system, created a new solution + project: tooltips work as expected
* On my system, even after deleting `.vs` folder:
  * FSharp.sln or VisualFSharp.sln: no tooltips for FSharp.Core
  * No text in many tooltips (like `"some string".Length` or `List.sum`) in _projects that have previously been opened_.

I understand that the latest change in 16.7.x was about two months ago (I thought we also joined the servicing releases, but it appears all changes, incl. bug fixes go in 16.8). This little fact makes it likely there's something amiss with my installation, I'll see what a Repair will do.

**Comment by abelbraaksma** [comment]
I restarted, cleaned all solutions, my own and the ones from FSharp repo: still the same. A repair takes quite some time, so I'll do that tonight, but I'm really wondering what the heck is going on here, as I cannot repo it in the VM at all.

**Comment by KevinRansom** [comment]
@abelbraaksma I see that it works correctly in 16.7.2 on my machine.  Does it always fail for you on all projects or just some, or does it start failing?

![image](https://user-images.githubusercontent.com/5175830/91776794-0d168e00-eba3-11ea-814a-1221782462b5.png)

If it fails for some projects could you try deleting the .vs folder in the projects folder and report whether that impacted the behaviour?

![image](https://user-images.githubusercontent.com/5175830/91776897-4a7b1b80-eba3-11ea-8860-e793ef25d9e8.png)

**Comment by abelbraaksma** [comment]
@KevinRansom, I did exactly that, deleting the `.vs` folder. I also restarted system, and cleaned, rebuild everything.

There are three solutions where it always happens, the two solutions of the F# repo don't show any tooltips for FSharp.Core members, but do for everything else. Another is a toy solution, with several very small projects, where only the doc comments of FSharp.Core members and types are missing, but signature is shown. Other solutions work fine.

It can be seen on my workstation, if I fire up a VM there's no problem. I'm now starting to wonder whether it has something to do with the vs preview being also installed there, as we've seen other issues with the side by s side behavior. The VM only has latest rtm, my workstation also latest preview.

**Comment by KevinRansom** [comment]
Really side by side works fine for pretty much everything.  The only real noticeable issue is dotnetsdk rolling forward to the highest dotnet sdk, and for sure that won't affect the VS ide.  I can believe that loading a project into rtm doing work, preview doing work and then going back to rtm might cause an issue, given that they would share project local caches, i.e the obj folder and the .vs folder.  But a project clean and deleting .vs folder would fix that.

If you could zip up the toy solution, in it's entirety we can take a look.

**Comment by abelbraaksma** [comment]
> But a project clean and deleting .vs folder would fix that

Exactly, that's how it's always been. This is the first time I can't get the quirks to disappear by doing that.

I'm mostly baffled by the fact that a git clean, rebuild of the F# repo doesn't fix this. In all honesty, it's been like that for a few weeks, but I thought it'd go away in the next point update. But now I hear it's not happening on other people's systems...

Maybe I should debug the 16.7 branch.

Let me try a few more things, like copying stuff over to another system, see if the behavior persists. Otherwise, if I can't repro on another machine, sending you a copy won't help much ;).

**Comment by cartermp** [comment]
I think we can close this out for now as it appears to have been a fluke of some kind.

**Comment by cartermp** [comment]
And by fluke I mean some kind of setup fluke, I suppose. Though they are rare

**Comment by abelbraaksma** [comment]
@cartermp, it is **not a fluke**, I'm afraid. It is reproducible.

 I just finished a full reinstall of VS 2019 16.7.2 and this had the following effect:

* Tooltips reappeared in my own solutions
* Still no tooltips at all for FSharp.Core functions inside any file in `VisualFSharp.sln` (that means, no tooltips on `Some` or `None` or `List.map` or `string` etc, but correct tooltips on anything not defined in FSharp.Core)

To be absolutely sure it is not something that _only happens on my system_, I downloaded a Win10 VM with VS 2019 pre-installed from Microsoft, upgraded VS to 16.7.2, download the F# repository, ran `build.cmd` and opened the `VisualFSharp.sln`. Then, after tooltips were loaded, you can see that they **do not appear for FSharp.Core members and types** (the file is `OperatorsModule1.fs`, but it is true for any other file in the solution):

![8932b1a1-b843-4655-96b8-b8df7d2b101e](https://user-images.githubusercontent.com/16015770/91877262-10327c80-ec7e-11ea-9a3e-03feae3d7e38.gif)
