### ISSUE TITLE
`string` function with StringBuilder or IFormattable that is null

### ISSUE THREAD

**Issue by atsapura** [dotnet/fsharp#10505]
```
let emptyStr = string null // works fine, yields ""

let (nullStr: string) = null

let nullResult = string nullStr // yields null
```

Expected result:
`string` function returns `""` and never `null`

* dotnet version: 5.0.100
* Operatin system: Windows 10 pro

EDIT:
Passing `null` as `StringBuilder` causes NRE:
```
> open System.Text;;
> let (sb: StringBuilder) = null;;
val sb : StringBuilder = <null>

> string sb;;
System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$FSI_0008>.$FSI_0008.main@()
Stopped due to error
```

**Comment by dsyme** [comment]
Yes, this is incorrect, it should be returning consistent values (the empty string in both cases)

**Comment by atsapura** [comment]
Judging by the code, NRE is possible for `IFormattable` reference types too.

Looks like the fix is quite simple. Instead of direct calling of `x.ToString()` we can use something like
```
    let inline safeToString<'a when 'a: not struct> x =
        match x with
        | null -> ""
        | x -> x.ToString()
```
but maybe I'm overlooking something

**Comment by cartermp** [comment]
This is actually a regression, this used to not be the case at least in F# 4.5.

**Comment by cartermp** [comment]
@atsapura I think we'd accept a PR to address this

**Comment by dsyme** [comment]
Fixed by #10505

**Comment by atsapura** [comment]
@dsyme That PR doesn't fix null for `StringBuilder` and nullable `IFormattable`. I'll try to make a PR, but the issue needs to be reopened, I believe.

**Comment by cartermp** [comment]
@atsapura feel free to open a PR if you think you know how to address it right now, in the meantime I'll open and rename the issue

**Comment by dsyme** [comment]
@atsapura You are right, see this comment https://github.com/dotnet/fsharp/pull/10553/files#r541997016

Would you like to make the fix?

**Comment by abelbraaksma** [comment]
Thanks for filling this and fixing this. I believe I may have introduced this bug when I worked on the `string` function to fix several other issues. At the time I created tests for quite a few scenarios, but clearly not enough, my apologies for that!
