### ISSUE TITLE
F# VS19 tooling does not work with FSharp.Data

### ISSUE THREAD

**Issue by nhirschey** [dotnet/fsharp#11294]
This is based on @jackfoxy's bug report here: https://github.com/fsprojects/FSharp.Data/issues/1361#issuecomment-803066047 

FSI and F# tooling works with FSharp.Data in Ionide, but while FSI in visual studio works with FSharp.Data, the tooling does not work. 

Jackfoxy found it with dotnet core scripting enabled, but I'm finding the same thing with old-style .NET framework 4.X scripting enabled.

To reproduce, try jackfoxy's example, but it is a problem in CsvProvider as well as my screenshots show:
```fsharp
#r "nuget: FSharp.Data"

open FSharp.Data

type TheJson = 
    JsonProvider<"""{"simple":"simpleValue","value":[{"Id":26,"simple_Number":"35-129-24115-0000"}]}""">
```

![image](https://user-images.githubusercontent.com/5226115/112162497-05244700-8be4-11eb-9afd-7d04d1aa5326.png)

I'm finding it in
- 16.8.5 with visual f# tools 16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
- 16.9.0 Preview 5 with visual f# tools 16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a

**Comment by cartermp** [comment]
I believe these design-time issues are resolved in the forthcoming preview of VS 16.10. Here's a build on my machine:

![image](https://user-images.githubusercontent.com/6309070/113054613-77ee6e80-915e-11eb-84c8-fee4d6130fb9.png)

From VS FSI:

![image](https://user-images.githubusercontent.com/6309070/113054667-8f2d5c00-915e-11eb-9611-6d3af52ec5bf.png)

**Comment by nhirschey** [comment]
This is still an issue on 16.10.0 Preview 2. I tried .net core scripting as well. Also an issue for me in 16.8.5.

![image](https://user-images.githubusercontent.com/5226115/116591625-f2a1d980-a916-11eb-8818-4ede1d5cf835.png)

![image](https://user-images.githubusercontent.com/5226115/116591645-ffbec880-a916-11eb-9cc7-a00d38719527.png)

**Comment by cartermp** [comment]
I think the fixes will be in preview 3. That's the builds I've been using internally for quite some time.
