### ISSUE TITLE
Crash when specifying package source in Visual Studio F# Interactive in .NET Framework mode

### ISSUE THREAD

**Issue by markpattison** [dotnet/fsharp#12033]
When using F# Interactive within Visual Studio, in .NET Framework mode, specifying an alternative NuGet package source crashes the session.

**Repro steps**

Using Visual Studio 16.11.1 on Windows 10 with the following F# Interactive options:

![image](https://user-images.githubusercontent.com/9657374/130642776-03950f50-c3d1-4aff-a67d-f6b27ec2f031.png)

1. Open F# Interactive
2. Enter `#i "nuget: https://sitecore.myget.org/F/sc-packages/api/v3/index.json";;`

Note - this is just an arbitrary public NuGet feed for the purposes of this bug report.

**Expected behavior**

Can now reference packages from that source.

**Actual behavior**

After a few seconds, the message `Session termination detected` appears.  Occasionally a `Process is terminated due to StackOverflowException` message appears first.

Pressing return starts a new session.

**Known workarounds**

This works fine in `fsi.exe` or `fsiAnyCpu.exe` from the command prompt, or when using .NET Core mode in Visual Studio.

**Comment by thinkbeforecoding** [comment]
This is still happening in Vs2022 (17.0.0 Preview 3.1). Any update on this ?

**Comment by markpattison** [comment]
I can confirm this also happens on my (totally separate) home PC running 16.11.2:

![image](https://user-images.githubusercontent.com/9657374/131383559-6b61ba33-a92a-41bc-b098-28c11a3b52a4.png)

**Comment by KevinRansom** [comment]
I am completely unable to reproduce this ...

I have tried VS2022 internal previews, and 16.11.2 and 16.11.3.  I have tried my main dev box and a clean sandbox, I just don't see the stack overflows.  Which is wierd since several of you are reporting this and @markpattison see's it on two different computers.

perhaps it's related to sdk's installed on the machine, please could you provide the results of running dotnet --info
````
C:\Users\WDAGUtilityAccount>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.401\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  5.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\WDAGUtilityAccount>
````
Thanks

Kevin

**Comment by thinkbeforecoding** [comment]
This happens only when "Use .Net core scripting" is false... so I don't know if it is related to sdk versions since it's not netcore.

**Comment by markpattison** [comment]
I agree @thinkbeforecoding 's comment, but for the record `dotnet --info` gives me the following:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.401\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by KevinRansom** [comment]
Guys,

we only use the dotnet sdk when resolving packages.  So ... it may impact it.

**Comment by markpattison** [comment]
Output from my home PC, where I also get the issue:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.413     
 Commit:    8387734958  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19041
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.413\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  2.1.818 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.119 [C:\Program Files\dotnet\sdk]
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All] 
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by markpattison** [comment]
According to Task Manager, Visual Studio is running `fsiAnyCpu.exe` from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools`.

It seems pretty interesting that, if I just run the exe from that location, it works fine.

**Comment by markpattison** [comment]
If it's any use - I also tried turning on "script debugging" which produced the following:
```

'fsiAnyCpu.exe' (CLR v4.0.30319: fsiAnyCpu.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: fsiAnyCpu.exe): Loaded 'c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\fsharp\Tools\fsiAnyCpu.exe'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: fsiAnyCpu.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: fsiAnyCpu.exe): Loaded 'c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\fsharp\Tools\FSharp.Compiler.Service.dll'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: fsiAnyCpu.exe): Loaded 'c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\fsharp\Tools\FSharp.Core.dll'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: fsiAnyCpu.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: fsiAnyCpu.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: fsiAnyCpu.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\c2b2eab3\182af5e1_be9dd701\fsiAnyCpu.exe'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\03bdf25e\3855f3e1_be9dd701\FSharp.Core.dll'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\663d9266\cf24eee1_be9dd701\FSharp.Compiler.Service.dll'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\2b74c850\eccad6e1_be9dd701\FSharp.Compiler.Interactive.Settings.dll'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\45b643b4\f744fbe1_be9dd701\Microsoft.Build.Utilities.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\dc473516\9c5ef8e1_be9dd701\Microsoft.Build.Framework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\e176adce\aaa8fae1_be9dd701\Microsoft.Build.Tasks.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\b3768f98\cd3cffe1_be9dd701\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'FSI-ASSEMBLY'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'FSI-ASSEMBLY.dll'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\ISymWrapper\v4.0_4.0.0.0__b03f5f7f11d50a3a\ISymWrapper.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\bee26b46\f2f1d6e1_be9dd701\FSharp.Compiler.Server.Shared.dll'. 
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x2170 has exited with code 0 (0x0).
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\4574dce1\aeeefee1_be9dd701\System.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\8a44d2cb\ea8affe1_be9dd701\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\37a31f20\b566f4e1_be9dd701\FSharp.DependencyManager.Nuget.dll'. 
The thread 0x3fd4 has exited with code 0 (0x0).
An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.dll

The program '[21004] fsiAnyCpu.exe' has exited with code -2147023895 (0x800703e9).
```

**Comment by markpattison** [comment]
On a second attempt. it only showed this:

```
The thread 0x42c8 has exited with code 0 (0x0).
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\4574dce1\aeeefee1_be9dd701\System.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\8a44d2cb\ea8affe1_be9dd701\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'fsiAnyCpu.exe' (CLR v4.0.30319: FSI_Domain): Loaded 'C:\Users\Mark\AppData\Local\assembly\dl3\8LWJ0GNK.2CJ\XC7VMCB6.0JJ\37a31f20\b566f4e1_be9dd701\FSharp.DependencyManager.Nuget.dll'. 
An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.dll

The program '[14476] fsiAnyCpu.exe' has exited with code -2147023895 (0x800703e9).
```

**Comment by KevinRansom** [comment]
@markpattison 
I cannot reproduce this at all.  Since you have a solid repro, can you please help me by:
1. Start Visual Studio
2. Open FSI window
3. Start a second Visual Studio
4. From the 2nd Visual Studio instance: attach a debugger to fsiAnyCpu.exe
5. From the 1st Visual Studio instance: cause the stack overflow
6. From the 2nd Visual Studio instance: Select Debug/Save Dump As ... to save a dump file
7. Send the dump file in for examination.

Attach it to a comment here would be useful, or email me a link to it somewhere on the web, codecutter@hotmail.com

Thank you for helping diagnose this

Kevin

**Comment by markpattison** [comment]
I've emailed you a link as requested - I couldn't get it to attach here.

**Comment by KevinRansom** [comment]
@markpattison ---

Thanks you for the dump it was very helpfull.

It is due to the Magic AssemblyResolve handling ... sigh!!!!  there is a reason it's called Magic.

![image](https://user-images.githubusercontent.com/5175830/134979254-9a6fd5ea-28b2-441d-a357-ea22ebb1596f.png)

I have no idea why on some machines this causes a stack overflow others it doesn't but I will see if I can figure out some hypothesis'

**Comment by markpattison** [comment]
Good luck!  In the meantime I'm trying to get all our internal libraries updated to be able to multi-target .NET 5...

**Comment by KevinRansom** [comment]
Hey @markpattison ,

still no clue, I have something else to try.  Could you please run fuslogvw and set the settings similar to:
put the file in a directory somewhere you can find it later, I used c:\temp\binds.bindlog
![image](https://user-images.githubusercontent.com/5175830/135138074-3be8aeac-ea87-41a2-b1a2-b3a01e6d5ed7.png)

Then run visual studio and repro the problem. and close VS.  put the logfile somewhere and send me a link.   Hopefully, I will be able get a bit further forward.

Thanks for doing this for me, it really helps

Kevin

**Comment by markpattison** [comment]
Done!  Thanks for your continued efforts!

**Comment by KevinRansom** [comment]
Thank you.

**Comment by KevinRansom** [comment]
@markpattison ,

thank you Mark, still no luck identifying a repro, although I have a theory.  Would you mind helping me out with another diagnostic:


1. Open a new command window
2. enter the following command
    ````set FSHARP_INTERACTIVE_PROGRESS=1````
3. Start Visual Studio
    ````devenv````
4. Open the fsi interactive window it should look similar to:
   ![image](https://user-images.githubusercontent.com/5175830/135352819-450c7897-4751-4829-bd18-4b206ea62c43.png)
5. #i "nuget: https://sitecore.myget.org/F/sc-packages/api/v3/index.json";;
6. It should look similar to:  
![image](https://user-images.githubusercontent.com/5175830/135353125-0ea94225-dc08-4185-aa62-1ffe28d2a2b3.png)
7. Could you copy all of the text in the fsi window to a text file and send me the file.

I am hoping to find lines similar to:
   "ATTEMPT MAGIC LOAD ON ASSEMBLY, simpleAssemName = %s" simpleAssemName 

I imagine that simpleAssemName will end with Microsoft.Build.Tasks.Core.resources and appear many many times.

Once again, thank you for sticking with this and helping us diagnose this issue

Kevin

**Comment by KevinRansom** [comment]
Aha ... I wonder if it's due to this:

Tools/**en-GB**/Microsoft.Build.Tasks.Core.resources.DLL
````
LOG: Attempting download of new URL file:///c:/program files (x86)/microsoft visual studio/2019/professional/common7/ide/commonextensions/microsoft/fsharp/Tools/en-GB/Microsoft.Build.Tasks.Core.resources.DLL.
LOG: Attempting download of new URL file:///c:/program files (x86)/microsoft visual studio/2019/professional/common7/ide/commonextensions/microsoft/fsharp/Tools/en-GB/Microsoft.Build.Tasks.Core.resources/Microsoft.Build.Tasks.Core.resources.DLL.
LOG: Attempting download of new URL file:///c:/program files (x86)/microsoft visual studio/2019/professional/common7/ide/commonextensions/microsoft/fsharp/Tools/en-GB/Microsoft.Build.Tasks.Core.resources.EXE.
LOG: Attempting download of new URL file:///c:/program files (x86)/microsoft visual studio/2019/professional/common7/ide/commonextensions/microsoft/fsharp/Tools/en-GB/Microsoft.Build.Tasks.Core.resources/Microsoft.Build.Tasks.Core.resources.EXE.
````
On my machine it's en-US which is the default and exists in the actual dll rather than a satellite assembly.

**Comment by KevinRansom** [comment]
Yep, reproed ...

![image](https://user-images.githubusercontent.com/5175830/135532302-41efdcc6-0e0f-489b-8d38-7b4da213642a.png)


It fails when a locale other than EN-US is applied.

**Comment by KevinRansom** [comment]
@markpattison thanks mate.

**Comment by markpattison** [comment]
Nice one!

**Comment by KevinRansom** [comment]
This will be fixed in 2019.11.6 --

![image](https://user-images.githubusercontent.com/5175830/137370558-ff6efb9f-8a5c-4675-a2a7-93dc733635a7.png)
