### ISSUE TITLE
Pre Build Nuget packages link no longer accessible

### ISSUE THREAD

**Issue by nojaf** [dotnet/fsharp#12704]
The link behind `versions` in the README (https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&view=versions&package=FSharp.Compiler.Service&protocolType=NuGet) brings me to an 401 page.

![image](https://user-images.githubusercontent.com/2621499/152750935-389e26a0-62d4-418c-9c17-bfe146fda9cc.png)

**Comment by vzarytovskii** [comment]
Hm, apparently, authentication is required now even for `dnceng/public` feed.
@mmitche do you maybe know if anonymous access is still possible?

**Comment by mmitche** [comment]
@nojaf are you able to see build results right now?

**Comment by mmitche** [comment]
I seem to be able to view build results, but not the artifacts pages. That said, I'm not sure what the old state of this was.

**Comment by nojaf** [comment]
Hey @mmitche, I was always able to see the build results of my PR's.
That is not really what I'm after here. I'd like to see the nightly NuGet feed again.
There are prerelease FCS packages that I'm interested in.
The link above used to lead me there, but that stopped working for me.

**Comment by mmitche** [comment]
@nojaf I think this should be resolved. Can you see this now?

**Comment by nojaf** [comment]
Hello @mmitche, no this still isn't working for me I'm afraid.
It redirects directly to a sign-in page.

**Comment by nojaf** [comment]
@vzarytovskii yes this seems to work now.
Thanks!
