### ISSUE TITLE
Cannot debug FSI with net 7 or .net framework in Visual Studio 2022 17.6.0 preview 2

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#15820]
For a while I haven't been able to debug scripts either by attaching to fsianycpu.exe or using the right click item on the F# interactive panel.

```fsharp
let xs = [1..100]

for i in xs do
  printfn $"{i}"
```

I am still able to step through code of loaded assemblies.

![image](https://github.com/dotnet/fsharp/assets/87944/d6a27916-f072-46cf-a0d6-d0c3b315f6b6)
![image](https://github.com/dotnet/fsharp/assets/87944/1e689e41-dd55-4739-b318-88afeff08ca5)

Microsoft Visual Studio Community 2022
Version 17.6.0 Preview 2.0
VisualStudio.17.Preview/17.6.0-pre.2.0+33513.286
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

ASP.NET and Web Tools   17.6.204.15292
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.6.204.15292
Azure App Service Tools v3.0.0

C# Tools   4.6.0-2.23151.17+1314d090671dc1a1500c5303c4b5ae9150f40d98
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   17.0.20302.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.6.0-2.23151.17+1314d090671dc1a1500c5303c4b5ae9150f40d98
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.6.0-beta.23126.1+4de2393866be1be6fa35af544c6f25a10af5ab3d
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

related: #14453

**Comment by T-Gro** [comment]
If you are on Version 17.**6**.0 Preview 2.0, can you please try in the latest preview?
The script debugging was fixed by Kevin earlier this year, this does look similar to it.

**Comment by smoothdeveloper** [comment]
I'm still seeing the same with Version 17.8.0 Preview 1.0

**Comment by smoothdeveloper** [comment]
@T-Gro, can I get confirmation this doesn't need a repro and that it also fail to debug on your end?

**Comment by T-Gro** [comment]
Yep, it also fails to debug on latest code from main.

**Comment by smoothdeveloper** [comment]
Related: #5457

**Comment by blfuentes** [comment]
Any news regarding this? I'm trying to debug some fsi and it shows me this window:
![image](https://github.com/dotnet/fsharp/assets/5121778/4bec4e30-5c40-4264-8b10-48f3dbcbc774)

**Comment by KevinRansom** [comment]
This should be fixed in 17.8 when it arrives.

https://github.com/dotnet/fsharp/assets/5175830/a29e1bcf-546e-4a43-a47d-2ae69d2117a0

**Comment by blfuentes** [comment]
> This should be fixed in 17.8 when it arrives.
> 
>  Recording.2023-10-14.165437.mp4

thanks!

**Comment by blfuentes** [comment]
> This should be fixed in 17.8 when it arrives.
> 
>  Recording.2023-10-14.165437.mp4

Seems it's nof fixed yet.
I'm running 17.8.1 with net 8 and still cannot debug FSI. I continue getting
![image](https://github.com/dotnet/fsharp/assets/5121778/12ac04dd-883f-4e24-a326-5f6848504d0d)

**Comment by majocha** [comment]
Same here. I had to resort to printf for debugging 😭

**Comment by KevinRansom** [comment]
So ... script debugging works for me if I disable "Just My Code".  Did you give that a try?

Uploading Recording 2024-01-03 184537.mp4…

**Comment by KevinRansom** [comment]
So ... script debugging works for me if I disable "Just My Code".  Did you give that a try?


Uploading Recording 2024-01-03 184537.mp4…

**Comment by majocha** [comment]
Same, @blfuentes. No locals, no watch, no values on hover, <Unknown function> on call stack.
With "Just my code" disabled I can step through code, which is something.

**Comment by KevinRansom** [comment]
@majocha, yes, locals, watch and values haven't worked for quite a while, we haven't got around to figuring out why - reasons, other issues mainly.  https://github.com/dotnet/fsharp/issues/14572

**Comment by KevinRansom** [comment]
I think we can close this right? we will manage the variables issue with this:  https://github.com/dotnet/fsharp/issues/14572

**Comment by smoothdeveloper** [comment]
I'm trying this again (have to demo fsx scripting to client), and reading to uncheck "Just My Code", as out of box, it doesn't work.

The issue I see is, I'm stepping through the FSI interpreter now, I don't think my client or F# script users wants to see this.

Is there a sense that things should work without "Just My Code" being unchecked, just out of the box (after setting the debugging option for F# Interactive being set)?

**Comment by smoothdeveloper** [comment]
<img width="635" alt="image" src="https://github.com/dotnet/fsharp/assets/87944/ad974cde-bf2a-45d7-8c55-80cb3b136109">

I mean, it is an excellent tactic to bring more developers, to contribute to this repository 🙂 but I think it will confuse end users basically.

Also, the fact that "Just My Code" has to be unchecked isn't obvious at all to figure out.
