### ISSUE TITLE
Intellisense and Quick Info do not show F# documentation in FSX files

### ISSUE THREAD

**Issue by theprash** [dotnet/fsharp#2926]
Version: VS 2017 Visual F# Tools v15.4.1.17042501

In FSX files only, Intellisense and Quick Info (hover tip) pop-ups show the type signature but not the summary documentation strings for F# core classes, modules and functions. However, the summary docs are displayed correctly for symbols defined by the user in F#, from F# libs and other .NET symbols.

#### Repro steps

Open an FSX file and type `List.ma`, or type `List.map` and hover over the `map` part.

![image](https://cloud.githubusercontent.com/assets/1362490/25431922/70b90386-2a7a-11e7-9885-c4a637c162ed.png)

![image](https://cloud.githubusercontent.com/assets/1362490/25432016/c31729e6-2a7a-11e7-9f5b-25786658d5f0.png)

You should see the doc string: "Builds a new collection whose elements...", but it's missing.

**Comment by realvictorprm** [comment]
Thanks @theprash 
I consider this the next thing I should try :smile:

**Comment by dsyme** [comment]
I believe this is because the default FSharp.Core reference used is the one on 

    C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0

which does not have FSharp.Core.xml alongside.  I think we should just install the XML alongside this, that is simplest.  The default reference text used is a fully qualified assembly name "FSharp.Core, Version=4.4.1.0..." computed by "GetFSharpCoreReferenceUsedByCompiler".  Prior to VS2017 (?) there was no FSharp.Core in the above directory and went to reference assemblies instead.

It's arguable we shouldn't be searching the above directory when resolving FSharp.Core, but that's hard because we have to include the directory in the assembly resolution search paths in order to resolve ``#r "FSharp.Compiler.Interactive.Settings.dll`` among others.

**Comment by dsyme** [comment]
Proposed fix is here https://github.com/Microsoft/visualfsharp/pull/2941

**Comment by dsyme** [comment]
Fix has been merged

**Comment by theprash** [comment]
Thank you!

**Comment by theprash** [comment]
@dsyme I'm on the latest VF# nightly and the problem remains. I don't have FSharp.Core.xml in the directory you mentioned. What should it take to fix this without manually copying the file?

**Comment by dsyme** [comment]
@theprash Just copy the file.  The VF# nightly doesn't install the file

**Comment by theprash** [comment]
@dsyme I can do that but I am thinking about fixing existing installations. Just to be clear, would this only be fixed in the next major VS update? Or only after a fresh VS install?

**Comment by dsyme** [comment]
> @dsyme  would this be fixed in the next major VS update? 

Yes I believe so

**Comment by theprash** [comment]
@dsyme This problem still remains for me in 15.3. I couldn't fix it with your suggested workaround either.

**Comment by vasily-kirichenko** [comment]
I confirm the bug is not fixed in 15.3 + today's nightly:

![image](https://user-images.githubusercontent.com/873919/29356233-4b7b27e8-827c-11e7-9f82-824141d1a76b.png)

![image](https://user-images.githubusercontent.com/873919/29356258-5c0f29ec-827c-11e7-9adc-08dd767ee754.png)

**Comment by dsyme** [comment]
@theprash @vasily-kirichenko Could you check if ``C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0`` has FSharp.Core.xml in your installation?  Thanks

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/29358725-bfb3f61e-8284-11e7-9043-d557ec92ce49.png)

**Comment by theprash** [comment]
I have the file there too (with the same modified date, so it's not one that I left there trying the workaround).

**Comment by dsyme** [comment]
@theprash @vasily-kirichenko OK, thanks.

**Comment by dsyme** [comment]
Here's the status of seeing docs from FSHarp.Core.xml in projects and scripts

```
16.4.5:
FSPROJ: YES
FSX: NO

16.4.5 with master installed into RoslynDev:
FSPROJ: NO
FSX: NO

16.5.0:
FSPROJ: YES
FSX: NO
```

**Comment by dsyme** [comment]
@cartermp I'm going over all issues and we really need to fix this one.

Currently people doing scripting in F# in Visual Studio just aren't seeing any documentation for FSharp.Core.   Of course experienced people don't notice this but beginners do.

I know this has been regressed a long time but it is a very basic part of the experience, otherwise there's no point in providing any XML docs at all.

On the whole we just have to make sure we don't regress this sort of thing, and if we do we fix it.

**Comment by cartermp** [comment]
Likely a setup thing, since FSharp.Core is a nuget package something needs to get updated to know to look there

**Comment by cartermp** [comment]
Updated workaround: copy FSharp.Core.xml into here:

`
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\FSharp
`

**Comment by cartermp** [comment]
Re-opening - something has regressed and it's no longer deployed, even though we explicitly deploy this now in our setup file.

**Comment by cartermp** [comment]
Okay, this appears as if it wasn't actually fixed - this apparently also needs ad adjustment: https://github.com/dotnet/fsharp/blob/release/dev16.8/vsintegration/Vsix/VisualFSharpFull/VisualFSharpFull.csproj#L28-L33
