### ISSUE TITLE
Running tests with -ci requires -excludeCIBinarylog switch, which doesn't exist

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9814]
I've been trying for a while to get tests running from the commandline using `build -testFSharpQA` and the like, to mimic the CI behavior, as I keep getting "works locally, but not remote" situations (and seeing PR discussions, I'm not alone in this).

I know the tests are being greatly refactored so this issue will run moot after some time, but for now, we'll have to live with his for a while to come. So I'm wondering if there's a solution for this:

## Repro steps

* Run `build -testFSharpQA -ci`

In the output, you'll get:

> ##vso\[task.logissue type=error](NETCORE_ENGINEERING_TELEMETRY=Build) Binary log must be enabled in CI build, or explicitly opted-out from with the -excludeCIBinarylog switch.

But this switch does not exist and will dump the help-output.

Full log:

```
D:\Projects\OpenSource\FSharp>build -testfsharpqa -ci
##vso[task.setvariable isSecret=False;variable=Artifacts;isOutput=True]D:\Projects\OpenSource\FSharp\artifacts
##vso[task.setvariable isSecret=False;variable=Artifacts.Toolset;isOutput=True]D:\Projects\OpenSource\FSharp\artifacts\toolset
##vso[task.setvariable isSecret=False;variable=Artifacts.Log;isOutput=True]D:\Projects\OpenSource\FSharp\artifacts\log\Debug
##vso[task.setvariable isSecret=False;variable=TEMP;isOutput=True]D:\Projects\OpenSource\FSharp\artifacts\tmp\Debug
##vso[task.setvariable isSecret=False;variable=TMP;isOutput=True]D:\Projects\OpenSource\FSharp\artifacts\tmp\Debug
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.302/dotnet-sdk-3.1.302-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.302/dotnet-sdk-3.1.302-win-x64.zip
dotnet-install: Adding to current process PATH: "D:\Projects\OpenSource\FSharp\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
##vso[task.prependpath]D:\Projects\OpenSource\FSharp\.dotnet
##vso[task.setvariable isSecret=False;variable=DOTNET_MULTILEVEL_LOOKUP;isOutput=True]0
##vso[task.setvariable isSecret=False;variable=DOTNET_SKIP_FIRST_TIME_EXPERIENCE;isOutput=True]1
##vso[task.logissue type=error](NETCORE_ENGINEERING_TELEMETRY=Build) Binary log must be enabled in CI build, or explicitly opted-out from with the -excludeCIBinarylog switch.
```

## Known workarounds

Would love to hear them! ;)

## More info

Note that running just `build -testFSharpQA` halts at some point and needs to be killed, or throws some weird error: https://github.com/dotnet/fsharp/issues/9613.

There's a mention here in `common/build.ps1`: https://github.com/dotnet/fsharp/blob/636052ac67898736f240845cddc1a808db773d73/eng/common/build.ps1#L62

**Comment by KevinRansom** [comment]
@abelbraaksma , because it was easy, I added it :-)

**Comment by KevinRansom** [comment]
oh -nobl oops, wrong accelerator, I should fix that.

**Comment by abelbraaksma** [comment]
@KevinRansom, something went wrong here or the issue came back, `-nobl` doesn't appear to work (anymore):

```
D:\Projects\OpenSource\FSharp>build -testCambridge -ci -nobl
Invalid argument: -nobl
```
